package convention

object PluginConstants {

    object Defaults {
        const val Android = "org.jetbrains.kotlin.android"
        const val Library = "com.android.library"
        const val ComposePlugin = "org.jetbrains.kotlin.plugin.compose"
        const val TestInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        const val ConsumerRules = "consumer-rules.pro"
        const val JavaLibrary = "java-library"
        const val MavenPublish = "maven-publish"
        const val ProguardRules = "proguard-rules.pro"
        const val ProguardAndroidRules = "proguard-android.txt"
    }

    object Projects {
        const val CONTRACT = ":contract"
        const val CORE = ":core"
        const val CORE_DATA = ":core:data"
        const val CORE_PRESENTATION = ":core:presentation"
        const val DATABASE = ":database"
        const val FEATURES = ":features"
        const val FEATURES_NEWS = ":features:news"
        const val FEATURES_NEWS_CONTRACT = ":features:news:contract"
        const val FEATURES_NEWS_DATA = ":features:news:data"
        const val FEATURES_NEWS_DOMAIN = ":features:news:domain"
        const val FEATURES_NEWS_PRESENTATION = ":features:news:presentation"
        const val LANGUAGE = ":language"
        const val NAVIGATION = ":navigation"
        const val NETWORK = ":network"
        const val UIKIT = ":uikit"
    }

    object Versions {
        const val Agp = "8.11.1"
        const val DetektFormatting = "1.23.8"
        const val Kotlin = "2.2.0"
        const val CoreKtx = "1.16.0"
        const val Junit = "4.13.2"
        const val JunitVersion = "1.2.1"
        const val EspressoCore = "3.6.1"
        const val KotlinxCoroutinesCore = "1.10.2"
        const val LeakcanaryAndroid = "2.14"
        const val LifecycleRuntimeKtx = "2.9.2"
        const val ActivityCompose = "1.10.1"
        const val ComposeBom = "2025.07.00"
        const val Ksp = "2.2.0-2.0.2"
        const val Hilt = "2.56.2"
        const val HiltCompiler = "1.2.0"
        const val HiltNavigationCompose = "1.2.0"
        const val JetbrainsKotlinJvm = "2.2.0"
        const val JavaxInject = "1"
        const val Airbnb_lottie = "6.6.7"
        const val Retrofit = "3.0.0"
        const val Okhttp = "5.1.0"
        const val LifecycleViewmodel = "2.9.2"
        const val Google_gson = "2.13.1"
        const val Serialization = "1.9.0"
        const val NavigationCompose = "2.9.2"
        const val RoomRuntime = "2.7.2"
        const val ConstraintlayoutCompose = "1.1.1"
        const val CoilCompose = "2.7.0"
        const val PagingCompose = "3.3.6"
        const val AccompanistPermissions = "0.37.3"
        const val Navigation3 = "1.0.0-alpha07"
        const val Chucker = "4.0.0"
        const val Test_junit_platform_runner = "1.13.4"
        const val Test_junit_jupiter_api = "5.13.4"
        const val Test_junit_jupiter_engine = "5.13.4"
        const val Test_arch_testing = "2.2.0"
        const val Test_json = "20250517"
        const val Test_mockito_kotlin = "6.0.0"
        const val Test_kotlinx_coroutines = "1.10.2"
        const val Test_mockk = "1.14.5"
        const val Test_turbine = "1.2.1"
        const val UiGraphics = "1.10.4"
    }

    object Libraries {
        const val AndroidxLifecycleViewmodel = "androidx.lifecycle.viewmodel"
        const val AndroidxCoreKtx = "androidx.core.ktx"
        const val DetektFormatting = "detekt.formatting"
        const val DetektRulesLibraries = "detekt.rules.libraries"
        const val DetektRulesAuthors = "detekt.rules.authors"
        const val Junit = "junit"
        const val AndroidxJunit = "androidx.junit"
        const val AndroidxEspressoCore = "androidx.espresso.core"
        const val AndroidxLifecycleRuntimeKtx = "androidx.lifecycle.runtime.ktx"
        const val AndroidxActivityCompose = "androidx.activity.compose"
        const val AndroidxComposeBom = "androidx.compose.bom"
        const val AndroidxUi = "androidx.ui"
        const val AndroidxUiGraphics = "androidx.ui.graphics"
        const val AndroidxUiTooling = "androidx.ui.tooling"
        const val AndroidxUiToolingPreview = "androidx.ui.tooling.preview"
        const val AndroidxMaterial3 = "androidx.material3"
        const val HiltAndroid = "hilt.android"
        const val HiltAndroidCompiler = "hilt.android.compiler"
        const val AndroidxHiltCompiler = "androidx.hilt.compiler"
        const val AndroidxHiltNavigationCompose = "androidx.hilt.navigation.compose"
        const val KotlinxCoroutinesCore = "kotlinx.coroutines.core"
        const val JavaxInject = "javax.inject"
        const val AirbnbLottie = "airbnb.lottie"
        const val LeakcanaryAndroid = "leakcanary.android"
        const val NetworkRetrofit = "network.retrofit"
        const val NetworkGsonConverter = "network.gson.converter"
        const val NetworkOkhttp = "network.okhttp"
        const val GoogleGson = "google.gson"
        const val KotlinSerializationJson = "kotlin.serialization.json"
        const val AndroidxNavigationCompose = "androidx.navigation.compose"
        const val AndroidxComposeMaterial3 = "androidx.compose.material3"
        const val AndroidxComposeUiUi = "androidx.compose.ui.ui"
        const val UiGraphics = "ui.graphics"
        const val UiTooling = "ui.tooling"
        const val AndroidxRoomRuntime = "androidx.room.runtime"
        const val AndroidxRoomCompiler = "androidx.room.compiler"
        const val AndroidxRoomKtx = "androidx.room.ktx"
        const val AndroidxRoomPaging = "androidx.room.paging"
        const val AndroidxConstraintlayoutCompose = "androidx.constraintlayout.compose"
        const val CoilCompose = "coil.compose"
        const val AndroidxPagingRuntimeKtx = "androidx.paging.runtime.ktx"
        const val AndroidxPagingCompose = "androidx.paging.compose"
        const val AccompanistPermissions = "accompanist.permissions"
        const val AndroidxNavigation3Runtime = "androidx.navigation3.runtime"
        const val AndroidxNavigation3Ui = "androidx.navigation3.ui"
        const val Chucker = "chucker"
        const val ChuckerNoop = "chucker.noop"
        const val AndroidGradlePlugin = "android.gradleplugin"
        const val KotlinGradlePlugin = "kotlin.gradleplugin"
        const val KspGradlePlugin = "ksp.gradleplugin"
        const val TestJunitPlatformRunner = "test.junit.platform.runner"
        const val TestJunitJupiter = "test.junit.jupiter"
        const val TestJunitJupiterApi = "test.junit.jupiter.api"
        const val TestJunitJupiterEngine = "test.junit.jupiter.engine"
        const val TestCoreTesting = "test.core.testing"
        const val TestJson = "test.json"
        const val TestMockitoKotlin = "test.mockito.kotlin"
        const val TestKotlinxCoroutines = "test.kotlinx.coroutines"
        const val TestMockk = "test.mockk"
        const val TestTurbine = "test.turbine"
        const val AndroidxComposeUiGraphics = "androidx.compose.ui.graphics"
        const val Network = "network"
        const val TestAll = "test.all"
        const val Detekt = "detekt"
    }

    object Plugins {
        const val AndroidApplication = "com.android.application"
        const val KotlinAndroid = "org.jetbrains.kotlin.android"
        const val KotlinCompose = "org.jetbrains.kotlin.plugin.compose"
        const val HiltAndroid = "com.google.dagger.hilt.android"
        const val Ksp = "com.google.devtools.ksp"
        const val AndroidLibrary = "com.android.library"
        const val JetbrainsKotlinJvm = "org.jetbrains.kotlin.jvm"
        const val KotlinSerialization = "org.jetbrains.kotlin.plugin.serialization"
        const val Detekt = "io.gitlab.arturbosch.detekt"
        const val CustomAndroidApplicationCompose = "gradlePlugins.android.application.compose"
        const val CustomAndroidLibraryCompose = "gradlePlugins.android.library.compose"
        const val CustomKotlinLibraryPure = "gradlePlugins.kotlin.library.pure"
        const val CustomAndroidLibraryData = "gradlePlugins.android.library.data"
        const val CustomKotlinLibraryDomain = "gradlePlugins.kotlin.library.domain"
        const val CustomKotlinLibraryContract = "gradlePlugins.kotlin.library.contract"
        const val CustomAndroidHiltLibrary = "gradlePlugins.android.library.hilt"
    }
}
